### ISSUE TITLE
where can I find lmdb/vocab_cache.pkl

### ISSUE THREAD

**Issue by lliwons** [YoungSeng/ReprGesture#1]
when I run synthesize.py, 
  File "synthesize.py", line 70, in main
    with open(vocab_cache_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/nfs7/y50021900/GENEA/genea_challenge_2022/dataset/v1_18_1/trn/lmdb/vocab_cache.pkl'

**Comment by YoungSeng** [comment]
It is a cache file generated by fasttext model, there are many lines to generate this file:

https://github.com/YoungSeng/ReprGesture/blob/effc047a6d207b5a484db6b45d3a41d9261edc3b/Tri/scripts/data_loader/lmdb_data_loader.py#L361

https://github.com/YoungSeng/ReprGesture/blob/effc047a6d207b5a484db6b45d3a41d9261edc3b/Tri/scripts/train.py#L530

However, I will upload my `vocab_cache` file tomorrow.

**Comment by YoungSeng** [comment]
I have uploaded it here: [vocab_cache.pkl](https://github.com/YoungSeng/ReprGesture/blob/main/dataset/vocab_cache.pkl), please check it out.
